modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "LGPL-3"

[[mods]]
modId = "matrix_test"
version = "${file.jarVersion}"
displayName = "Architectury Test"
authors = "shedaniel"
description = '''
A intermediary api aimed to ease developing multiplatform mods.
'''
license = "LGPL-3"